//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoparts.Api.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autoparts.Api.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria.
        /// </summary>
        public static string CATEGORY {
            get {
                return ResourceManager.GetString("CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria com ID {0} não foi encontrada.
        /// </summary>
        public static string CATEGORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("CATEGORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente.
        /// </summary>
        public static string CLIENT {
            get {
                return ResourceManager.GetString("CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente com ID {0} não foi encontrado.
        /// </summary>
        public static string CLIENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("CLIENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmação.
        /// </summary>
        public static string COMMIT {
            get {
                return ResourceManager.GetString("COMMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha na confirmação.
        /// </summary>
        public static string COMMIT_FAILED_MESSAGE {
            get {
                return ResourceManager.GetString("COMMIT_FAILED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email é obrigatório.
        /// </summary>
        public static string EMAIL_IS_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro de validação de domínio.
        /// </summary>
        public static string ERROR_DOMAIN {
            get {
                return ResourceManager.GetString("ERROR_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao excluir a categoria.
        /// </summary>
        public static string FAILED_TO_DELETE_CATEGORY {
            get {
                return ResourceManager.GetString("FAILED_TO_DELETE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao excluir o cliente.
        /// </summary>
        public static string FAILED_TO_DELETE_CLIENT {
            get {
                return ResourceManager.GetString("FAILED_TO_DELETE_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao excluir o fabricante.
        /// </summary>
        public static string FAILED_TO_DELETE_MANUFACTORER {
            get {
                return ResourceManager.GetString("FAILED_TO_DELETE_MANUFACTORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao excluir o produto.
        /// </summary>
        public static string FAILED_TO_DELETE_PRODUCT {
            get {
                return ResourceManager.GetString("FAILED_TO_DELETE_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível excluir a compra.
        /// </summary>
        public static string FAILED_TO_DELETE_PURCHASE {
            get {
                return ResourceManager.GetString("FAILED_TO_DELETE_PURCHASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao excluir a devolução.
        /// </summary>
        public static string FAILED_TO_DELETE_RETURN {
            get {
                return ResourceManager.GetString("FAILED_TO_DELETE_RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao excluir a venda.
        /// </summary>
        public static string FAILED_TO_DELETE_SALE {
            get {
                return ResourceManager.GetString("FAILED_TO_DELETE_SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao excluir o fornecedor.
        /// </summary>
        public static string FAILED_TO_DELETE_SUPPLIER {
            get {
                return ResourceManager.GetString("FAILED_TO_DELETE_SUPPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor inserido deve ser maior que zero..
        /// </summary>
        public static string GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID não encontrado:.
        /// </summary>
        public static string ID_NOT_FOUND {
            get {
                return ResourceManager.GetString("ID_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Token de acesso ou token de atualização inválido.
        /// </summary>
        public static string INVALID_ACCESS_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_ACCESS_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de cálculo inválido.
        /// </summary>
        public static string INVALID_CALCULATION_TYPE {
            get {
                return ResourceManager.GetString("INVALID_CALCULATION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número do CNPJ informado é inválido..
        /// </summary>
        public static string INVALID_CNPJ {
            get {
                return ResourceManager.GetString("INVALID_CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número do CPF informado é inválido..
        /// </summary>
        public static string INVALID_CPF {
            get {
                return ResourceManager.GetString("INVALID_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credenciais inválidas.
        /// </summary>
        public static string INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email inválido.
        /// </summary>
        public static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome de usuário ou senha inválidos.
        /// </summary>
        public static string INVALID_LOGIN {
            get {
                return ResourceManager.GetString("INVALID_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A chave secreta JWT não está configurada..
        /// </summary>
        public static string INVALID_SECRET_KEY {
            get {
                return ResourceManager.GetString("INVALID_SECRET_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fabricante.
        /// </summary>
        public static string MANUFACTORER {
            get {
                return ResourceManager.GetString("MANUFACTORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fabricante com ID {0} não foi encontrado.
        /// </summary>
        public static string MANUFACTORER_NOT_FOUND {
            get {
                return ResourceManager.GetString("MANUFACTORER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O texto excedeu o limite de 100 caracteres..
        /// </summary>
        public static string MAX_LENGTH_100 {
            get {
                return ResourceManager.GetString("MAX_LENGTH_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O texto excedeu o limite de 14 caracteres..
        /// </summary>
        public static string MAX_LENGTH_14 {
            get {
                return ResourceManager.GetString("MAX_LENGTH_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O texto excedeu o limite de 255 caracteres..
        /// </summary>
        public static string MAX_LENGTH_255 {
            get {
                return ResourceManager.GetString("MAX_LENGTH_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O texto excedeu o limite de 50 caracteres..
        /// </summary>
        public static string MAX_LENGTH_50 {
            get {
                return ResourceManager.GetString("MAX_LENGTH_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome é obrigatório.
        /// </summary>
        public static string NAME_IS_REQUIRED {
            get {
                return ResourceManager.GetString("NAME_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esta informação é necessária.
        /// </summary>
        public static string NOT_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("NOT_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produto.
        /// </summary>
        public static string PRODUCT {
            get {
                return ResourceManager.GetString("PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O produto com ID {0} não foi encontrado..
        /// </summary>
        public static string PRODUCTS_NOT_FOUND {
            get {
                return ResourceManager.GetString("PRODUCTS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Insira o produto.
        /// </summary>
        public static string PRODUCTS_REQUIRED {
            get {
                return ResourceManager.GetString("PRODUCTS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Compra.
        /// </summary>
        public static string PURCHASE {
            get {
                return ResourceManager.GetString("PURCHASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A compra com o ID {0} não foi encontrada..
        /// </summary>
        public static string PURCHASE_NOT_FOUND {
            get {
                return ResourceManager.GetString("PURCHASE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Devolução.
        /// </summary>
        public static string RETURN {
            get {
                return ResourceManager.GetString("RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A devolução com o ID {0} não foi encontrada..
        /// </summary>
        public static string RETURN_NOT_FOUND {
            get {
                return ResourceManager.GetString("RETURN_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum dado encontrado.
        /// </summary>
        public static string RETURN_NULL {
            get {
                return ResourceManager.GetString("RETURN_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O perfil {0} já existe..
        /// </summary>
        public static string ROLE_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("ROLE_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Perfil criado.
        /// </summary>
        public static string ROLE_CREATED {
            get {
                return ResourceManager.GetString("ROLE_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Venda.
        /// </summary>
        public static string SALE {
            get {
                return ResourceManager.GetString("SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Venda com ID {0} não foi encontrada.
        /// </summary>
        public static string SALES_NOT_FOUND {
            get {
                return ResourceManager.GetString("SALES_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SKU.
        /// </summary>
        public static string SKU {
            get {
                return ResourceManager.GetString("SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao gerar o SKU.
        /// </summary>
        public static string SKU_FAILED {
            get {
                return ResourceManager.GetString("SKU_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estoque.
        /// </summary>
        public static string STOCK {
            get {
                return ResourceManager.GetString("STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha no cálculo do estoque.
        /// </summary>
        public static string STOCK_FAILED_MESSAGE {
            get {
                return ResourceManager.GetString("STOCK_FAILED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estoque insuficiente.
        /// </summary>
        public static string STOCK_INSUFFICIENT {
            get {
                return ResourceManager.GetString("STOCK_INSUFFICIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sem estoque.
        /// </summary>
        public static string STOCK_ZERO {
            get {
                return ResourceManager.GetString("STOCK_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fornecedor.
        /// </summary>
        public static string SUPPLIER {
            get {
                return ResourceManager.GetString("SUPPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Fornecedor com ID {0} não foi encontrada.
        /// </summary>
        public static string SUPPLIER_NOT_FOUND {
            get {
                return ResourceManager.GetString("SUPPLIER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário criado.
        /// </summary>
        public static string USER_CREATED {
            get {
                return ResourceManager.GetString("USER_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário com o ID {0} não foi encontrado..
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário adicionado perfil.
        /// </summary>
        public static string USER_TO_ROLE {
            get {
                return ResourceManager.GetString("USER_TO_ROLE", resourceCulture);
            }
        }
    }
}
