//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoparts.Api.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autoparts.Api.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Commit.
        /// </summary>
        public static string COMMIT {
            get {
                return ResourceManager.GetString("COMMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Commit failed.
        /// </summary>
        public static string COMMIT_FAILED_MESSAGE {
            get {
                return ResourceManager.GetString("COMMIT_FAILED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Domain validation error.
        /// </summary>
        public static string ERROR_DOMAIN {
            get {
                return ResourceManager.GetString("ERROR_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The value entered must be greater than zero.
        /// </summary>
        public static string GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID Not Found:.
        /// </summary>
        public static string ID_NOT_FOUND {
            get {
                return ResourceManager.GetString("ID_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid Calculation Type.
        /// </summary>
        public static string INVALID_CALCULATION_TYPE {
            get {
                return ResourceManager.GetString("INVALID_CALCULATION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ Number Proivided is Invalid.
        /// </summary>
        public static string INVALID_CNPJ {
            get {
                return ResourceManager.GetString("INVALID_CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF Number Proivided is Invalid.
        /// </summary>
        public static string INVALID_CPF {
            get {
                return ResourceManager.GetString("INVALID_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The text exceeded the 100 character limit.
        /// </summary>
        public static string MAX_LENGTH_100 {
            get {
                return ResourceManager.GetString("MAX_LENGTH_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The text exceeded the 14 character limit.
        /// </summary>
        public static string MAX_LENGTH_14 {
            get {
                return ResourceManager.GetString("MAX_LENGTH_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The text exceeded the 255 character limit.
        /// </summary>
        public static string MAX_LENGTH_255 {
            get {
                return ResourceManager.GetString("MAX_LENGTH_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The text exceeded the 50 character limit.
        /// </summary>
        public static string MAX_LENGTH_50 {
            get {
                return ResourceManager.GetString("MAX_LENGTH_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This information is required.
        /// </summary>
        public static string NOT_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("NOT_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No data found.
        /// </summary>
        public static string RETURN_NULL {
            get {
                return ResourceManager.GetString("RETURN_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Insufficient Stock.
        /// </summary>
        public static string STOCK_INSUFFICIENT {
            get {
                return ResourceManager.GetString("STOCK_INSUFFICIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UPDATE Products
        ///SET Stock = StockMovements.Stock
        ///FROM (
        ///    SELECT 
        ///        ProductId,
        ///        SUM(Quantity) AS Stock
        ///    FROM (
        ///        SELECT ProductId, Quantity FROM PurchaseProducts
        ///        UNION ALL
        ///        SELECT ProductId, Quantity FROM ReturnProducts
        ///        UNION ALL
        ///        SELECT ProductId, -Quantity AS Quantity FROM SaleProducts
        ///    ) AS Movements
        ///    GROUP BY ProductId
        ///) AS StockMovements
        ///WHERE Products.ProductId = StockMovements.ProductId;
        ///
        ///
        ///
        ///.
        /// </summary>
        public static string UpdateStock {
            get {
                return ResourceManager.GetString("UpdateStock", resourceCulture);
            }
        }
    }
}
